#!/usr/bin/python3

import serial
import matplotlib.pyplot as plt

with serial.Serial('/dev/ttyUSB0', 115200, timeout=1) as ser:
    data = []
    while True :
        line = ser.readline()   # read a '\n' terminated line
        aline = line.split()
        if len(aline) in { 0, 1 } :
            continue
        if aline[2] == b'0.000A' :
            continue
        print( aline )
        data.append( aline[1] )
        if len( data ) == 5000 :
            plt.plot( data )
            plt.ylabel('some numbers')
            plt.show()

